/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContentRouteImport } from './routes/app.content'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/content': typeof AppContentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/content': typeof AppContentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/content': typeof AppContentRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/enterprise'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/content'
    | '/app/dashboard'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/enterprise'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/content'
    | '/app/dashboard'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/enterprise'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/content'
    | '/app/dashboard'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApproachRoute: typeof ApproachRoute
  BlogRoute: typeof BlogRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContentRoute: typeof AppContentRoute
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContentRoute: AppContentRoute,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApproachRoute: ApproachRoute,
  BlogRoute: BlogRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
