/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnterpriseIndexRouteImport } from './routes/enterprise.index'
import { Route as ControlCenterIndexRouteImport } from './routes/control-center.index'
import { Route as EnterpriseTeamRouteImport } from './routes/enterprise.team'
import { Route as EnterpriseOverviewRouteImport } from './routes/enterprise.overview'
import { Route as EnterpriseComplianceRouteImport } from './routes/enterprise.compliance'
import { Route as EnterpriseBrandRulesRouteImport } from './routes/enterprise.brand-rules'
import { Route as EnterpriseApprovalsRouteImport } from './routes/enterprise.approvals'
import { Route as EnterpriseAnalyticsRouteImport } from './routes/enterprise.analytics'
import { Route as ControlCenterWorkflowsRouteImport } from './routes/control-center.workflows'
import { Route as ControlCenterUsersRouteImport } from './routes/control-center.users'
import { Route as ControlCenterSupportRouteImport } from './routes/control-center.support'
import { Route as ControlCenterRoadmapRouteImport } from './routes/control-center.roadmap'
import { Route as ControlCenterRevenueRouteImport } from './routes/control-center.revenue'
import { Route as ControlCenterIncidentsRouteImport } from './routes/control-center.incidents'
import { Route as ControlCenterApprovalsRouteImport } from './routes/control-center.approvals'
import { Route as ControlCenterAgentsRouteImport } from './routes/control-center.agents'
import { Route as BlogArticleRouteImport } from './routes/blog.article'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPublishingRouteImport } from './routes/app.publishing'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppContentIndexRouteImport } from './routes/app.content.index'
import { Route as AppContentReviewRouteImport } from './routes/app.content.review'
import { Route as AppContentNewRouteImport } from './routes/app.content.new'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseIndexRoute = EnterpriseIndexRouteImport.update({
  id: '/enterprise/',
  path: '/enterprise/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterIndexRoute = ControlCenterIndexRouteImport.update({
  id: '/control-center/',
  path: '/control-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseTeamRoute = EnterpriseTeamRouteImport.update({
  id: '/enterprise/team',
  path: '/enterprise/team',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseOverviewRoute = EnterpriseOverviewRouteImport.update({
  id: '/enterprise/overview',
  path: '/enterprise/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseComplianceRoute = EnterpriseComplianceRouteImport.update({
  id: '/enterprise/compliance',
  path: '/enterprise/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseBrandRulesRoute = EnterpriseBrandRulesRouteImport.update({
  id: '/enterprise/brand-rules',
  path: '/enterprise/brand-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseApprovalsRoute = EnterpriseApprovalsRouteImport.update({
  id: '/enterprise/approvals',
  path: '/enterprise/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseAnalyticsRoute = EnterpriseAnalyticsRouteImport.update({
  id: '/enterprise/analytics',
  path: '/enterprise/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterWorkflowsRoute = ControlCenterWorkflowsRouteImport.update({
  id: '/control-center/workflows',
  path: '/control-center/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterUsersRoute = ControlCenterUsersRouteImport.update({
  id: '/control-center/users',
  path: '/control-center/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterSupportRoute = ControlCenterSupportRouteImport.update({
  id: '/control-center/support',
  path: '/control-center/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRoadmapRoute = ControlCenterRoadmapRouteImport.update({
  id: '/control-center/roadmap',
  path: '/control-center/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRevenueRoute = ControlCenterRevenueRouteImport.update({
  id: '/control-center/revenue',
  path: '/control-center/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterIncidentsRoute = ControlCenterIncidentsRouteImport.update({
  id: '/control-center/incidents',
  path: '/control-center/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterApprovalsRoute = ControlCenterApprovalsRouteImport.update({
  id: '/control-center/approvals',
  path: '/control-center/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterAgentsRoute = ControlCenterAgentsRouteImport.update({
  id: '/control-center/agents',
  path: '/control-center/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleRoute = BlogArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishingRoute = AppPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentReviewRoute = AppContentReviewRouteImport.update({
  id: '/content/review',
  path: '/content/review',
  getParentRoute: () => AppRoute,
} as any)
const AppContentNewRoute = AppContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/publishing': typeof AppPublishingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/training': typeof AppTrainingRoute
  '/app/voice': typeof AppVoiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/control-center/agents': typeof ControlCenterAgentsRoute
  '/control-center/approvals': typeof ControlCenterApprovalsRoute
  '/control-center/incidents': typeof ControlCenterIncidentsRoute
  '/control-center/revenue': typeof ControlCenterRevenueRoute
  '/control-center/roadmap': typeof ControlCenterRoadmapRoute
  '/control-center/support': typeof ControlCenterSupportRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/control-center/workflows': typeof ControlCenterWorkflowsRoute
  '/enterprise/analytics': typeof EnterpriseAnalyticsRoute
  '/enterprise/approvals': typeof EnterpriseApprovalsRoute
  '/enterprise/brand-rules': typeof EnterpriseBrandRulesRoute
  '/enterprise/compliance': typeof EnterpriseComplianceRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/team': typeof EnterpriseTeamRoute
  '/control-center/': typeof ControlCenterIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/app/content/new': typeof AppContentNewRoute
  '/app/content/review': typeof AppContentReviewRoute
  '/app/content/': typeof AppContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/publishing': typeof AppPublishingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/training': typeof AppTrainingRoute
  '/app/voice': typeof AppVoiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/control-center/agents': typeof ControlCenterAgentsRoute
  '/control-center/approvals': typeof ControlCenterApprovalsRoute
  '/control-center/incidents': typeof ControlCenterIncidentsRoute
  '/control-center/revenue': typeof ControlCenterRevenueRoute
  '/control-center/roadmap': typeof ControlCenterRoadmapRoute
  '/control-center/support': typeof ControlCenterSupportRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/control-center/workflows': typeof ControlCenterWorkflowsRoute
  '/enterprise/analytics': typeof EnterpriseAnalyticsRoute
  '/enterprise/approvals': typeof EnterpriseApprovalsRoute
  '/enterprise/brand-rules': typeof EnterpriseBrandRulesRoute
  '/enterprise/compliance': typeof EnterpriseComplianceRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/team': typeof EnterpriseTeamRoute
  '/control-center': typeof ControlCenterIndexRoute
  '/enterprise': typeof EnterpriseIndexRoute
  '/app/content/new': typeof AppContentNewRoute
  '/app/content/review': typeof AppContentReviewRoute
  '/app/content': typeof AppContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/blog': typeof BlogRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/publishing': typeof AppPublishingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/training': typeof AppTrainingRoute
  '/app/voice': typeof AppVoiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/article': typeof BlogArticleRoute
  '/control-center/agents': typeof ControlCenterAgentsRoute
  '/control-center/approvals': typeof ControlCenterApprovalsRoute
  '/control-center/incidents': typeof ControlCenterIncidentsRoute
  '/control-center/revenue': typeof ControlCenterRevenueRoute
  '/control-center/roadmap': typeof ControlCenterRoadmapRoute
  '/control-center/support': typeof ControlCenterSupportRoute
  '/control-center/users': typeof ControlCenterUsersRoute
  '/control-center/workflows': typeof ControlCenterWorkflowsRoute
  '/enterprise/analytics': typeof EnterpriseAnalyticsRoute
  '/enterprise/approvals': typeof EnterpriseApprovalsRoute
  '/enterprise/brand-rules': typeof EnterpriseBrandRulesRoute
  '/enterprise/compliance': typeof EnterpriseComplianceRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/team': typeof EnterpriseTeamRoute
  '/control-center/': typeof ControlCenterIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/app/content/new': typeof AppContentNewRoute
  '/app/content/review': typeof AppContentReviewRoute
  '/app/content/': typeof AppContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/accounts'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/library'
    | '/app/publishing'
    | '/app/settings'
    | '/app/support'
    | '/app/training'
    | '/app/voice'
    | '/blog/$slug'
    | '/blog/article'
    | '/control-center/agents'
    | '/control-center/approvals'
    | '/control-center/incidents'
    | '/control-center/revenue'
    | '/control-center/roadmap'
    | '/control-center/support'
    | '/control-center/users'
    | '/control-center/workflows'
    | '/enterprise/analytics'
    | '/enterprise/approvals'
    | '/enterprise/brand-rules'
    | '/enterprise/compliance'
    | '/enterprise/overview'
    | '/enterprise/team'
    | '/control-center/'
    | '/enterprise/'
    | '/app/content/new'
    | '/app/content/review'
    | '/app/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/accounts'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/library'
    | '/app/publishing'
    | '/app/settings'
    | '/app/support'
    | '/app/training'
    | '/app/voice'
    | '/blog/$slug'
    | '/blog/article'
    | '/control-center/agents'
    | '/control-center/approvals'
    | '/control-center/incidents'
    | '/control-center/revenue'
    | '/control-center/roadmap'
    | '/control-center/support'
    | '/control-center/users'
    | '/control-center/workflows'
    | '/enterprise/analytics'
    | '/enterprise/approvals'
    | '/enterprise/brand-rules'
    | '/enterprise/compliance'
    | '/enterprise/overview'
    | '/enterprise/team'
    | '/control-center'
    | '/enterprise'
    | '/app/content/new'
    | '/app/content/review'
    | '/app/content'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/approach'
    | '/blog'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/report'
    | '/signup'
    | '/solutions'
    | '/app/accounts'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/library'
    | '/app/publishing'
    | '/app/settings'
    | '/app/support'
    | '/app/training'
    | '/app/voice'
    | '/blog/$slug'
    | '/blog/article'
    | '/control-center/agents'
    | '/control-center/approvals'
    | '/control-center/incidents'
    | '/control-center/revenue'
    | '/control-center/roadmap'
    | '/control-center/support'
    | '/control-center/users'
    | '/control-center/workflows'
    | '/enterprise/analytics'
    | '/enterprise/approvals'
    | '/enterprise/brand-rules'
    | '/enterprise/compliance'
    | '/enterprise/overview'
    | '/enterprise/team'
    | '/control-center/'
    | '/enterprise/'
    | '/app/content/new'
    | '/app/content/review'
    | '/app/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApproachRoute: typeof ApproachRoute
  BlogRoute: typeof BlogRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  ControlCenterAgentsRoute: typeof ControlCenterAgentsRoute
  ControlCenterApprovalsRoute: typeof ControlCenterApprovalsRoute
  ControlCenterIncidentsRoute: typeof ControlCenterIncidentsRoute
  ControlCenterRevenueRoute: typeof ControlCenterRevenueRoute
  ControlCenterRoadmapRoute: typeof ControlCenterRoadmapRoute
  ControlCenterSupportRoute: typeof ControlCenterSupportRoute
  ControlCenterUsersRoute: typeof ControlCenterUsersRoute
  ControlCenterWorkflowsRoute: typeof ControlCenterWorkflowsRoute
  EnterpriseAnalyticsRoute: typeof EnterpriseAnalyticsRoute
  EnterpriseApprovalsRoute: typeof EnterpriseApprovalsRoute
  EnterpriseBrandRulesRoute: typeof EnterpriseBrandRulesRoute
  EnterpriseComplianceRoute: typeof EnterpriseComplianceRoute
  EnterpriseOverviewRoute: typeof EnterpriseOverviewRoute
  EnterpriseTeamRoute: typeof EnterpriseTeamRoute
  ControlCenterIndexRoute: typeof ControlCenterIndexRoute
  EnterpriseIndexRoute: typeof EnterpriseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/': {
      id: '/enterprise/'
      path: '/enterprise'
      fullPath: '/enterprise/'
      preLoaderRoute: typeof EnterpriseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/': {
      id: '/control-center/'
      path: '/control-center'
      fullPath: '/control-center/'
      preLoaderRoute: typeof ControlCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/team': {
      id: '/enterprise/team'
      path: '/enterprise/team'
      fullPath: '/enterprise/team'
      preLoaderRoute: typeof EnterpriseTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/overview': {
      id: '/enterprise/overview'
      path: '/enterprise/overview'
      fullPath: '/enterprise/overview'
      preLoaderRoute: typeof EnterpriseOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/compliance': {
      id: '/enterprise/compliance'
      path: '/enterprise/compliance'
      fullPath: '/enterprise/compliance'
      preLoaderRoute: typeof EnterpriseComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/brand-rules': {
      id: '/enterprise/brand-rules'
      path: '/enterprise/brand-rules'
      fullPath: '/enterprise/brand-rules'
      preLoaderRoute: typeof EnterpriseBrandRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/approvals': {
      id: '/enterprise/approvals'
      path: '/enterprise/approvals'
      fullPath: '/enterprise/approvals'
      preLoaderRoute: typeof EnterpriseApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/analytics': {
      id: '/enterprise/analytics'
      path: '/enterprise/analytics'
      fullPath: '/enterprise/analytics'
      preLoaderRoute: typeof EnterpriseAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/workflows': {
      id: '/control-center/workflows'
      path: '/control-center/workflows'
      fullPath: '/control-center/workflows'
      preLoaderRoute: typeof ControlCenterWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/users': {
      id: '/control-center/users'
      path: '/control-center/users'
      fullPath: '/control-center/users'
      preLoaderRoute: typeof ControlCenterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/support': {
      id: '/control-center/support'
      path: '/control-center/support'
      fullPath: '/control-center/support'
      preLoaderRoute: typeof ControlCenterSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/roadmap': {
      id: '/control-center/roadmap'
      path: '/control-center/roadmap'
      fullPath: '/control-center/roadmap'
      preLoaderRoute: typeof ControlCenterRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/revenue': {
      id: '/control-center/revenue'
      path: '/control-center/revenue'
      fullPath: '/control-center/revenue'
      preLoaderRoute: typeof ControlCenterRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/incidents': {
      id: '/control-center/incidents'
      path: '/control-center/incidents'
      fullPath: '/control-center/incidents'
      preLoaderRoute: typeof ControlCenterIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/approvals': {
      id: '/control-center/approvals'
      path: '/control-center/approvals'
      fullPath: '/control-center/approvals'
      preLoaderRoute: typeof ControlCenterApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center/agents': {
      id: '/control-center/agents'
      path: '/control-center/agents'
      fullPath: '/control-center/agents'
      preLoaderRoute: typeof ControlCenterAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/article': {
      id: '/blog/article'
      path: '/article'
      fullPath: '/blog/article'
      preLoaderRoute: typeof BlogArticleRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publishing': {
      id: '/app/publishing'
      path: '/publishing'
      fullPath: '/app/publishing'
      preLoaderRoute: typeof AppPublishingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/': {
      id: '/app/content/'
      path: '/content'
      fullPath: '/app/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/review': {
      id: '/app/content/review'
      path: '/content/review'
      fullPath: '/app/content/review'
      preLoaderRoute: typeof AppContentReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/new': {
      id: '/app/content/new'
      path: '/content/new'
      fullPath: '/app/content/new'
      preLoaderRoute: typeof AppContentNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPublishingRoute: typeof AppPublishingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppContentNewRoute: typeof AppContentNewRoute
  AppContentReviewRoute: typeof AppContentReviewRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPublishingRoute: AppPublishingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppContentNewRoute: AppContentNewRoute,
  AppContentReviewRoute: AppContentReviewRoute,
  AppContentIndexRoute: AppContentIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogArticleRoute: typeof BlogArticleRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogArticleRoute: BlogArticleRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApproachRoute: ApproachRoute,
  BlogRoute: BlogRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  ControlCenterAgentsRoute: ControlCenterAgentsRoute,
  ControlCenterApprovalsRoute: ControlCenterApprovalsRoute,
  ControlCenterIncidentsRoute: ControlCenterIncidentsRoute,
  ControlCenterRevenueRoute: ControlCenterRevenueRoute,
  ControlCenterRoadmapRoute: ControlCenterRoadmapRoute,
  ControlCenterSupportRoute: ControlCenterSupportRoute,
  ControlCenterUsersRoute: ControlCenterUsersRoute,
  ControlCenterWorkflowsRoute: ControlCenterWorkflowsRoute,
  EnterpriseAnalyticsRoute: EnterpriseAnalyticsRoute,
  EnterpriseApprovalsRoute: EnterpriseApprovalsRoute,
  EnterpriseBrandRulesRoute: EnterpriseBrandRulesRoute,
  EnterpriseComplianceRoute: EnterpriseComplianceRoute,
  EnterpriseOverviewRoute: EnterpriseOverviewRoute,
  EnterpriseTeamRoute: EnterpriseTeamRoute,
  ControlCenterIndexRoute: ControlCenterIndexRoute,
  EnterpriseIndexRoute: EnterpriseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
